### PR TITLE
added Splash Screen

### PR DESCRIPTION
**Pull request by mahikaw**
Created a splash screen which displays the logo of the app till the app is starting instead of a blank screen.
Addresses #177 partly.
device-2016-12-16-233332

### CODE REVIEW

**Comment by anubhakushwaha** [comment]
@mahikawason Please refrain from sending PR's without getting an approval from the same by any of the mentors.Either create a new issue or comment on a free issue asking the mentors to assign you.This way your hard work will be used up for the right task needed by the project.Thanks.

**Comment by mahikawason** [comment]
@anubhakushwaha , this is already an issue and I didn't want to create a duplicate issue. However, I will keep this in my mind for future. 
@chhavip please review.

**Comment by codingblazer** [comment]
Hey @mahikawason 
In issue #177 , I was waiting for the mentors approval (I mentioned in the issue that I would like to work on it). Anyway, addition of splash is not the intended feature but for future please ask before creating PR. :)

**Comment by mahikawason** [comment]
Hi @codingblazer , I'm a bit new to all this and didn't know that something of that sorts has to be taken care of. I will bear this in mind for future.

**Comment by codingblazer** [comment]
@mahikawason No problem, it happens :)

**Pull request closed without merging**
