### PR TITLE
outreachy work

### PR DESCRIPTION
**Pull request by debanjanah**
issue #544

### CODE REVIEW

**Comment by Rimjhim28** [comment]
@MeepyMay @thisum @asclepiusgal @debanjanah @m-murad I think this PR needs to be merged.

**Comment by m-murad** [comment]
@Rimjhim28 @debanjanah 
Can you please tell what is the purpose of saving the images in the repo?

This will increase the size of the already bloated repo. Can we save it someplace else or is it necessary to save it here?

**Comment by debanjanah** [comment]
@m-murad it was how designs were documented previously, and also to keep tabs on what changed throughout the process, get feedback and to make it easy for newcomers to contribute to design. 
There is a drive folder as well though. We should discuss this on slack. It's true the repo will only keep increasing in size!

**Comment by Rimjhim28** [comment]
@m-murad @debanjanah I didn't know much about that. All I thought was if thisPR contains designs that are not yet present in develop branch, new accessories, newly designed NPCs, then this needs to be merged to develop the new features during GSoC.

**Pull request merged**
