### PR TITLE
incorporated proper layout in differnet devices

### PR DESCRIPTION
**Pull request by mahikaw**
fixed errors of slight misalignment and overlapping, apart from the "answers" list view in gamactivity which had a slightly faulty layout.
Addresses #232 
@chhavip please review. Thanks :smile:

### CODE REVIEW

**Comment by mahikaw** [comment]
A gentle reminder :)

**Comment by chhavip** [comment]
@mahikaw Please fix the merge conflicts that have occurred and the PR should be good to merge.

**Comment by mahikaw** [comment]
Please check now. @chhavip thanks :)

**Comment by chhavip** [comment]
Squash the commits.

**Comment by mahikaw** [comment]
I don't have access to this branch unfortunately. Could you please squash and merge it?

**Comment by chhavip** [comment]
@mahikaw , please preserve your version of code in future. Merging for now but that is not the proper development process. Thanks for your contribution!

**Comment by mahikaw** [comment]
Thanks @chhavip , will surely keep it in mind for future. :)

**Pull request merged**
