### PR TITLE
Adapt gamemap.xml for phones and Tablet in portrait and landscape mode

### PR DESCRIPTION
**Pull request by vasukiarunachalam**
I made few changes to gamemap.xml to make it generalised for all dimensions. The dimens.xml for phones and tablets were defined in following folders .
For phones -
values/dimens.xml
values-land/dimens.xml

For 7" Tablets -
values-sw600dp/dimens.xml
values-sw600dp-port/dimens.xml

For 10" Tablets -
values-sw720dp/dimens.xml
values-sw720dp-port/dimens.xml

### CODE REVIEW

**Comment by vasukiarunachalam** [comment]
I created a new pull request with my changes. I reverted the previous commit to resolve conflicts. But I am not sure why it is still displaying ? 

Regarding changes in gamemap.xml -
I defined button sizes for each place rather than having one click-width and click-height.
I also made map-alpha defined in dimens.xml.
I made few changes to the alignment of buttons.

Please let me know if it is correct.

**Comment by alma-castant** [comment]
@vasukiarunachalam the code looks good, but I will have to test this before being able to merge it.
It currently has conflicts that you need to resolve so I can do so.

For solving the conflicts, you need to pull from master by doing `git pull` and resolve the conflicts in the conflicting files manually. Then you will need to add the files using `git add file_name` and commit using `git commit --amend`. 
After you do that, as you currently have 7 commits, I recommend you to save the files you made changes to in a separate folder and create a new branch for this feature where you work with one commit only. First checkout master by doing `git checkout master` and then create your new branch by doing `git checkout -b branch_name`. This way your branch doesn't include the commits you had in other branches. Then include your changes and continue with the process for creating a new pull request as explained in the README file. If you haven't set your remote repository to the systers master branch, you can follow the instructions for it on the README file. 

Let me know if you have any questions ;)

**Comment by vasukiarunachalam** [comment]
Hi, I am bit stuck with making a single commit for this feature. I have the systers/powerup in my upstream. I fetched it and made changes to it and committed. But my remote repository origin/master still has 7 commits in it. How to discard the 7 commits and push only one commit ? Should I again fork , clone and then commit , push ?

**Comment by alma-castant** [comment]
@vasukiarunachalam you should always create a new branch before making changes so you don't have commits in master. To remove them now, you can follow the instructions [here](http://stackoverflow.com/questions/1338728/delete-commits-from-a-branch-in-git).

**Pull request closed without merging**
