### PR TITLE
Show Snackbar on selection of inappropriate choice (Google Code-in task)

### PR DESCRIPTION
**Pull request by jacqueline8711**

### CODE REVIEW

**Comment by anubhakushwaha** [comment]
@chhavip **This is an approved GCI task** *link to the task* https://codein.withgoogle.com/dashboard/task-instances/5993335537795072/

**Comment by chhavip** [comment]
Can be merged.

**Comment by anubhakushwaha** [comment]
@chhavip This can be merged.

**Comment by aanchal07** [comment]
Closing the pull request since there are conflicts.

**Pull request closed without merging**
