### PR TITLE
updated errors in questions

### PR DESCRIPTION
**Pull request by mahikaw**
#222 fixed.

device-2016-12-20-110145

### CODE REVIEW

**Comment by mahikawason** [comment]
These files are already tracked by git inspite of being added to gitignore. I have created a PR to fix this. Please review. @chhavip  #213

**Comment by chhavip** [comment]
That will not change the fact that you have already committed your files in this, even if that PR is merged, files from this one will come in which is not required. Please remove for consideration of merge.

**Comment by mahikaw** [comment]
That is not an issue @chhavip. I will rebase it once you merge PR #213 :smile:

**Comment by chhavip** [comment]
@mahikaw I will not be merging this PR in its current condition. Upto you if you wish to fix it or not.

**Comment by mahikaw** [comment]
@chhavip , I have removed the .iml and .idea files as per your say, however, this one vcs.xml is not changing. The same is the issue with PR #226 I would be grateful if you could help me in sorting this out. Thnaks a lot :)

**Comment by mahikaw** [comment]
I have created a PR from a new branch as the vcs.xml wasn't getting updated. Please review @chhavip

**Pull request closed without merging**
