### PR TITLE
Added MapActivityTest #85

### PR DESCRIPTION
**Pull request by opticod**
#85

### CODE REVIEW

**Comment by alma-castant** [comment]
Please @opticod describe the fix in the PR body and commit message, not only a link to the issue

**Comment by opticod** [comment]
@alma-castant This is a Espresso based UI testing class of `MapActivity` .This will test different Views and Buttons shown up in different orientations including landscape and portrait ,and the working of different click events on Buttons.

**Comment by alma-castant** [comment]
Please apply the comments I left in other similar PRs

**Comment by aanchal07** [comment]
Changes pending since very long so closing.

**Pull request closed without merging**
