### PR TITLE
Fixed the lag on press of Home button

### LINKED ISSUE #1374: Time lag on press of home button in AboutActivity
## Description
On the press of home button in AboutActivity, there is a lag of a short time before it opens another acitivty.

## Mocks
WhatsApp Video 2020-03-06 at 1 13 45 AM

### Update [Required]
There should be no delay on click of home button

### PR DESCRIPTION
**Pull request by pknotfound**
### Description
Fixed lag on press of home button in aboutactivity

Fixes #1374

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Tested on OnePlus6t

### CODE REVIEW

**Comment by atm1504** [comment]
@Priyansh-Kedia the title of your pr doesnot say anything about the pr u created or the issue solved in this pr. Please follow the proper guidelines. Checkout here: https://github.com/anitab-org/powerup-android/pull/1349#issuecomment-598364416

**Comment by atm1504** [comment]
@Priyansh-Kedia you created 3 commits.
1st: added 2 lines
2nd: removed those 2 lines
3rd: Again added the 2 lines
Why so??
Squash the commits. Also, attach a gif to show that the code actually solved the issue

**Review by atm1504 — CHANGES_REQUESTED** [review]
@Priyansh-Kedia you created 3 commits.
1st: added 2 lines
2nd: removed those 2 lines
3rd: Again added the 2 lines
Why so??
Squash the commits. Also, attach a gif to show that the code actually solved the issue

**Comment by pknotfound** [comment]
@atm1504 
Actually my android studio stopped midway, that is why I had to add the new commits.

**Comment by atm1504** [comment]
@Priyansh-Kedia it should be something like this: ```fix: Fix lag on the press of home button```

**Comment by pknotfound** [comment]
@atm1504 
I will take care of it from the next time
Thanks

**Comment by sammy1997** [comment]
@Priyansh-Kedia Please squash the commits

**Comment by pknotfound** [comment]
> @Priyansh-Kedia Please squash the commits

@sammy1997 
I cannot squash the commits as I made this PR some time back and had to re fork the git repository due to some reasons.
I would be willing to open a new PR for the same.

Please guide.
Thanks

**Comment by sammy1997** [comment]
Ok. I am closing the PR in that case.

**Pull request closed without merging**
