### PR TITLE
Added Splash screen

### PR DESCRIPTION
**Pull request by medhach**
A splash screen added to give a simple additional look to the app.

### CODE REVIEW

**Comment by alma-castant** [comment]
Hi @medhach I am not sure this splash screen is a good idea. It prevents the user from doing anything from a while and doesn't provide any benefits. An introductory tutorial explaining the user what to do in the game that would open only the first time would be better as it would actually provide a benefit teaching the user how to play and wouldn't bother the user once they have already played ;)

**Comment by medhach** [comment]
Will work on the introductory tutorial. Thank you!

**Comment by alma-castant** [comment]
You should claim the task here: https://github.com/systers/powerup-android/issues/31
Since the task is very visual, I would recommend sketching it first, either with pen and paper or with more professional tools like Balsamiq, Photoshop or Illustrator (don't put too much effort on making it pixel perfect, but use it as a tool for planning what you are going to build and getting feedback)

**Comment by medhach** [comment]
[IntroScreens.pdf](https://github.com/systers/powerup-android/files/59529/IntroScreens.pdf)
I have made these screens as the introduction screens. These could be shown the first time the app is opened by the user.
I have tried to keep the content simple and small, but do let me know if I should change it. :)

**Pull request closed without merging**
