### PR TITLE
Create a screen for "Not Enough Points" condition

### PR DESCRIPTION
**Pull request by InfernoCoder**
I fixed [this issue](https://github.com/systers/powerup-android/issues/170) and this is the PR.

### CODE REVIEW

**Comment by InfernoCoder** [comment]
THE LATEST COMMIT IS THE FINAL COMMIT ON THIS PR.

**Comment by aanchal07** [comment]
Please add only the required commit in the PR. Add only the commit for "not enough points" and remove the commits for snackbar.(Hint: Create a new branch from your origin and add only the required changes for this particular feature)

**Comment by InfernoCoder** [comment]
Due to problems in my fork, I'm deleting my fork and then I'll start again (I already have my code backed up). Sorry for this, I'll post new PR in 1-3 hrs.

**Comment by InfernoCoder** [comment]
@aanchal07 Created [the PR](https://github.com/systers/powerup-android/pull/193) neatly from start this time :) .

**Pull request closed without merging**
