### PR TITLE
Rectified selection of store items

### LINKED ISSUE #1272: Without purchasing from the store, changes are still applied
## Description
As a tester, if the player doesn't buy anything from the store but just tested, changes should not be applied until the player buy that. If bought, then the points should be reduced correctly.  

## Mocks

To recreate the issue:
1. Score more than 5 points and go to the store
2. Click on any item (from any of the 3 categories) but don't purchase. You will see the changes will be applied to the avatar. 
3. After resume the play, the changes will be still applied to the avatar. 

## Acceptance Criteria
- [ ] unless purchased, changes should not be applied to the avatar
- [ ] when the user clicks "maybe not" in the dialog (when clicking on an item), the changes should revert. 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by Rimjhim28**
### Description
When an item is clicked on store and it is not bought, first the warning dialog appears and then on confirming the purchase the item is set on the avatar.

Fixes #1272 

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Rimjhim28** [comment]
@thisum  I have not even changed that file in my PR and I don't know how to rectify this. 
I will contact @geekanamika regarding this.

**Comment by thisum** [comment]
@Rimjhim28, let's see whether @debanjanah or @asclepiusgal can build the program, if so then no problem. Anyway there's a merge conflict reported. pls resolve it.

**Comment by asclepiusgal** [comment]
@Rimjhim28 is this working for you?

**Comment by thisum** [comment]
@Rimjhim28, the DatabaseHandler class has been removed when replacing the db handler function by @geekanamika. @geekanamika can you resolve the error and send a PR

**Comment by Rimjhim28** [comment]
@asclepiusgal The app works perfect for me without any crashes

**Pull request merged**
