### PR TITLE
Save chosen options

### LINKED ISSUE #1150: Save user chosen pre game setup characters
## Description
As a developer,
I need save the npcs that user have chosen,
so that the asker in the game activity is updated accordingly.

## Mocks
Not applicable

### Update [Required]
- [ ] Save the chosen option in PowerUpUtils.java

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 hours

### PR DESCRIPTION
**Pull request by Rimjhim28**
### Description
Included the logic to save user's selected options for the scenario NPCs using static variables in SessionHistory.java

Fixes #1150 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

I used log messages to check that the values are updated correctly.

npc_log_msgs

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by ExactlyMay** [comment]
@m-murad @manjumegh We have a couple mentors on PowerUp Android that are on vacation. If you two have some time to review, I would appreciate the support.

**Comment by m-murad** [comment]
@Rimjhim28 
What you have done will add both png and webp images to the repo history.
In the repo history, you can see that both files are present there. Please edit the previous commits.

**Comment by Rimjhim28** [comment]
@m-murad 
This is how it shows to me on terminal
commit history
It's delete with png and create with webP.
Even in files changed, png images are with red highlights, so I thought they git removed.
Do you want me to do something else?

**Comment by m-murad** [comment]
Exactly, the git should not know about the png files that you added in the previous commits. Deleting the files will not help (because they are already in the branch history and bloat the repo), you will have to reset the commit in which you added the images

**Comment by Rimjhim28** [comment]
But that was done on a previous PR and it is merged. So I caonverted them to webP here. It was my mistake that I missed on these three images while moving all the images.

**Pull request merged**
