### PR TITLE
Fix #361 Updated Avatar shown after buying items from store

### LINKED ISSUE #361: Avatar not updated after shopping at store in Game Activity
The avatar doesn't get updated after buying in the store.

before buying:-
device-2017-03-21-205218

After buying:-
device-2017-03-21-205350

device-2017-03-21-210619

@aanchal07 @chhavip Can I go ahead with a PR?

### PR DESCRIPTION
**Pull request by codingblazer**
**Issue #361** - Updated avatar is shown in the game after buying items from the store.

### CODE REVIEW

**Comment by aanchal07** [comment]
@codingblazer Please send separate PRs for separate issues.

**Comment by codingblazer** [comment]
@aanchal07 Sure

**Comment by codingblazer** [comment]
@aanchal07 This solution will not work until #377 is resolved. I have checked this before the point #377 was merged and it's working great.

**Comment by aanchal07** [comment]
Not required now.

**Pull request closed without merging**
