### PR TITLE
ADDED VOICE TO TEXT

### PR DESCRIPTION
**Pull request by Mandeepsinghchadha**
Description
To make the game more interactive ,user friendly and more reachable to varied mass of people I have 
added google voice  in every scenario for every conversation clicked by the user

Fixes # [ISSUE]
#977 

Type of Changes
Added the text to speech function and its dependencies in the code base of the app

Checklist
1)My PR Follows the style guidelines of this project
2)My changes generate no warning

Code/Quality assurance
1) New feature (Non breaking changes which adds a new functionality)

How Has this Been Tested
1) I have tested it on 3-4 emulators and my android device

### CODE REVIEW

**Comment by Mandeepsinghchadha** [comment]
@MeepyMay Hii I have removed the unwanted empty else conditions and framed my PR according to the guidelines.If there is any further change I have to do kindly suggest me I will see to it.

**Comment by Mandeepsinghchadha** [comment]
@anubhakushwaha  I have changed the code can you kindly review it.

**Comment by sammy1997** [comment]
@Mandeepsinghchadha You have unrelated commits in the same PR. I guess this is against contributing guidelines. Am I right @anubhakushwaha ?

**Comment by Mandeepsinghchadha** [comment]
@sammy1997  can you just tell me what are the unrelated commits you are talking  about ?

**Comment by sammy1997** [comment]
@Mandeepsinghchadha The xml file in your commit is dated December 31st. Moreover I guess that's not related to TTS. So I think it shouldn't be there. Correct me if I am wrong.

**Pull request closed without merging**
