### PR TITLE
Fixes #1102 Redundant throws clause 22/22

### LINKED ISSUE #1102: Fix lint errors
## Description
As a maintainer,
I need remove the lint errors in the code,
so that the overall code structure and app performance can be improved.

## Mocks
Not applicable

### Update 

The warnings/error that need to fixed are
- [ ] Android Resource Validation ( 8 errors )
- [ ] Extraneous text in resource file ( 1 waining )
- [ ] Missing commit() on SharedPreference editor ( 4 warnings )
- [ ] Wrong Resource Type ( 4 warnings )
- [ ] Hardcoded text ( 27 warnings )
- [ ] TextView Internationalization ( 18 warnings )
- [ ] Using left/right instead of start/end attributes ( 3 warnings )
- [ ] FrameLayout can be replaced with <merge> tag ( 5 warnings )
- [ ] Missing baselineAligned attribute ( 5 warnings )
- [ ] Obsolete layout params ( 5 warnings )
- [ ] Pointless boolean expression ( 4 warnings )
- [ ] Redundant local variable ( 4 warnings )
- [ ] Declaration can have final modifier ( 27 warnings )
- [ ] Method can be void ( 1 warning )
- [x] Redundant throws clause ( 22 warnings )
- [x] Unused import ( 40 warnings )
- [ ] 'if' replaceable with 'switch' ( 3 warnings )
- [x] Unused XML schema declaration ( 5 warnings )

**Note** : Only of the above listed items can be claimed and fixed by one contributor

## Definition of Done
- [ ] One of the required item is completed
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by smieras**
### Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes # [1102]

### Type of Change:
- Quality Assurance

**Code/Quality Assurance Only**
- n/a

### How Has This Been Tested?
Could not actually compile the source code due to gradle / intellij not recognizing the java directories as source folders. However the removal of the redundant throws clauses in the unit tests, should not cause anything to break.

### Checklist:
- [ ] My PR follows the style guidelines of this project

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by Rimjhim28 — APPROVED** [review]
Nice work! For your future PRs, also modify the description according to the changes.

**Comment by smieras** [comment]
Thanks for the feedback, first time for me to fill in a contribution template like that and I kinda messed up there, my bad.

**Review by geekanamika — APPROVED** [review]
Looks good to me.

**Comment by geekanamika** [comment]
@Rimjhim28 Do you have the merge access? If yes, merge this PR else tag someone who can approve/merge it.

**Review by Rimjhim28 — APPROVED** [review]

**Pull request merged**
