### PR TITLE
Added image resources in standard Android sizes

### PR DESCRIPTION
**Pull request by riddhik84**
Resolved issue #141 

Added all images as of (21/08/2016) in standard Android sizes.

### CODE REVIEW

**Comment by chhavip** [comment]
Great work! Small correction, remove the background resources for all screen sizes as the standard one is big enough to cover the entire screen in each scenario.

**Comment by riddhik84** [comment]
You mean background.png and back_background.png correct? Any other files than these?

**Comment by chhavip** [comment]
Just these two would do. Also could you check the increase in size of the application once upon adding the image resources so we can make the decision whether we should add all or remove multiple resources for some of the less used ones.

**Comment by riddhik84** [comment]
As mentioned here: https://developer.android.com/training/basics/supporting-devices/screens.html we will not require any of the images in ldpi. I will remove all ldpi images and also background image correction as mentioned above. I will then check the size of the apk and update.

**Comment by riddhik84** [comment]
After making above changes I created an apk and the size of apk is 14.8MB. The apk size looks ok as of now.

**Comment by chhavip** [comment]
@riddhik84 , thank you for the research and adding images, will discuss this with the team once as the current size is nearly 3mbs and we will have to see if we can make the changes or not and come up with alternatives in the other case, your contribution is appreciated!

**Pull request closed without merging**
