### PR TITLE
created espresso test of UI

### PR DESCRIPTION
**Pull request by arpnakumari**
This is .java file of Espresso. Since i tested it on my real android device through USB and not on emulator so I don't have the video.

### CODE REVIEW

**Comment by arpnakumari** [comment]
espresso-testing

I have this screenshot of my AS while testing.

**Comment by anubhakushwaha** [comment]
@arpnakumari Hey,you can use this app to record your demo https://play.google.com/store/apps/details?id=com.hecorat.screenrecorder.free&hl=en and then share the video with us.

**Comment by codingblazer** [comment]
@arpnakumari Or use android studio itself to record on device. 
[Record in AS](http://stackoverflow.com/questions/31547350/how-to-record-screen-with-android-studio)

**Comment by aanchal07** [comment]
Conflicts in the PR.

**Pull request closed without merging**
