### PR TITLE
Modifies Database and Adds Store Activity

### PR DESCRIPTION
**Pull request by codingblazer**
This Pull request adds New store activity and required changes -

1. The database has been modified - Some utility functions in DBHandler class related to telepathy and health powers are deleted. Also, since now we have one accessory at a time, I have changed the Avatar Entry Table by removing the COLUMN_BAG and adding the COLUMN_ACCESSORY. This column will keep account of currently set accessory to the avatar. 

This was needed because now we can have many accessories i.e. They won't be just limited to the bag, necklace, etc. That's why we can't have separate columns for each accessory. I made a general column i.e. COLUMN_ACCESSORY for them.

2. I have made changes to .csv files which are used to fill database for the first time. Since accessories model is changed and quantity of new items like hair are changed, I have changed them accordingly.

3. For Store Activity, I have used GridView for showing items where each item is a custom Linear Layout. The view for items is in other xml file - store_selection_view.xml

4. I have used 2 drawable for every accessory and dress. One is needed for the avatar and other is needed for each item box. I tried using one version only but that required cropping and resizing of each item image (24 images) dynamically and this conversion is a heavy process which leads to OutOfMemory Exception. It was a trade off between performance and 72 kb of space. I went with performance.

### CODE REVIEW

**Comment by aanchal07** [comment]
PR looks good. Since a lot of files have been changed, cannot go through them all. Tested the PR on emulator and it runs fine.

**Comment by aanchal07** [comment]
@codingblazer The app crashes on pressing store.

Screenshot:
image

This says:  java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams

**Comment by codingblazer** [comment]
@aanchal07 I have made the changes !! Please review it :)

**Comment by aanchal07** [comment]
@codingblazer  Works now!
Merging this one.

**Pull request merged**
