### PR TITLE
Converted library version in to variables in Gradle

### PR DESCRIPTION
**Pull request by mamatagelanee07**
1. Converted support library versions to variable so we need to update only variable when new version available
2. Changed mockito version 1.+ to specific version as we should define a specific version (Version like 1.+ will check every time in a 24 hour if new version is available, which increases Gradle build time )
3. Updated version to latest one

### CODE REVIEW

**Comment by codingblazer** [comment]
Hi, @mamatagelanee07. It seems valid to me (we will check this soon). 
(Please create an issue first in future. Read this if you haven't already. [Guide](https://github.com/systers/powerup-android/wiki/How-to-Contribute)). Thanks.

**Comment by mamatagelanee07** [comment]
Hi Sachin,

Thanks for consideration. I tried to reach on slack and syster's mail list
too. Can you send me an invitation for slack, so that I can discuss issue
there first and then log it to Github?

Thanks,
Mamata Gelanee

**Comment by codingblazer** [comment]
Hi, you can join slack by inviting yourself - [Systers Slack Inviter](http://systers.io/slack-systers-opensource/)

**Comment by mamatagelanee07** [comment]
Hi Sachin,

Got invitation!

Thanks,
Mamata Gelanee

On Sep 28, 2017 10:12 PM, "Sachin Aggarwal" <notifications@github.com>
wrote:

Hi, you can join slack by inviting yourself - Systers Slack Inviter
<http://systers.io/slack-systers-opensource/>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/systers/powerup-android/pull/490#issuecomment-332894793>,
or mute the thread

**Pull request closed without merging**
