### PR TITLE
Fix gradle dependencies

### LINKED ISSUE #1051: No layout preview in xml files
## Description
As a user,
I need update the gradle dependecies version, tagetSdkVersion and compileSdkVersion,
so that the layouts are properly displayed in xml files.

## Mocks
error log
no layout views

### Update 
- [ ] Fix the gradle dependencies

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 minutes

### PR DESCRIPTION
**Pull request by Rimjhim28**
### Description
Fixed gradle dependencies such that the layout preview is available

Fixes #1051 

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
The code has been tested on Android Studio emulator

layout

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Rimjhim28** [comment]
@m-murad Please have a look.

**Comment by m-murad** [comment]
Travis is failing. Please check what's wrong

**Comment by Rimjhim28** [comment]
@m-murad The code works properly on my machine. Can you please help me with the error.

**Comment by m-murad** [comment]
@Rimjhim28 
I see what the problem is.
You will have to update [this](https://github.com/systers/powerup-android/blob/develop/.travis.yml#L8) to tell Travis that you have changed the `tragetSdkversion`.

**Comment by Rimjhim28** [comment]
@m-murad Done! Thanks for the help.

**Comment by m-murad** [comment]
@Rimjhim28 
I have already approved the PR. Someone will merge it soon. Thanks for the PR.

**Pull request merged**
