### PR TITLE
code cleanup

### PR DESCRIPTION
**Pull request by mahikaw**
Adresses #134

### CODE REVIEW

**Comment by mahikaw** [comment]
There were other images with the same contents as these but different names. So I deleted the copies.

**Comment by chhavip** [comment]
@mahikaw, resolve the conflicts created.

**Comment by mahikaw** [comment]
@chhavip conflicts resolved. Ready to merge. :)

**Comment by mahikaw** [comment]
A gentle reminder.

**Comment by mahikaw** [comment]
A gentle reminder @chhavip @anubhakushwaha

**Comment by aanchal07** [comment]
@mahikaw Can you resolve the conflicts again?

**Comment by aanchal07** [comment]
Conflicts in the PR.

**Pull request closed without merging**
