### PR TITLE
Added Replay feature to ScenarioOverActivity

### PR DESCRIPTION
**Pull request by InfernoCoder**
This PR is from the GCI Tasks list and adds the feature to replay games.

### CODE REVIEW

**Comment by anubhakushwaha** [comment]
@chhavip **This is an approved GCI task** *link to the approved task* https://codein.withgoogle.com/dashboard/task-instances/6203924988035072/

**Comment by chhavip** [comment]
@anubhakushwaha , how many instances of same are left?

**Comment by anubhakushwaha** [comment]
@chhavip I updated the link to the approved task,it was by mistake put wrong and zero claims are left now.

**Comment by aanchal07** [comment]
Closing the pull request since there are conflicts.

**Pull request closed without merging**
