### PR TITLE
added avatar customization assets

### PR DESCRIPTION
**Pull request by debanjanah**
Braided hairstyle (African hairstyle) added. The aim is to promote diversity & inclusion.

### CODE REVIEW

**Comment by MeepyMay** [comment]
@kimhwins I think most in-ear headphones fit the style with less detail, still the cartoon, flat 2D design that's current. My concern is the around the neck headphones have shading on the cushion part that makes it more 3D. Then, the dress I'd remove sleeve details and neck details. I'm absolutely not sure on the blouse with the cloud pattern. I'm checking with African friends about the hair.

TLDR:

- In-ear headphones - Great!
- Switch current over-ear headphones to less layers [like this](https://image.freepik.com/free-icon/striped-headphones_318-40301.jpg) or [this](https://i.pinimg.com/736x/58/9a/ec/589aecde47111d0cee6fdfb692cefc93.jpg).
- Surgical masks - Great!
- Green dress, remove the leaf detail on sleeves and on the neck. remove shade on top, change shade at bottom to bold black lines.
- Orange blouse, not sure about the texture, but there's a little orange on the bottom left that's outside of the lines.
- African hairstyle, on pause. Looking to African friends to see if they relate to the hairstyle.

**Comment by MeepyMay** [comment]
@debanjanah If you send in a new PR for in-ear headphones and surgical masks, then I can merge. If you can change the shade lines to a couple black lines to show a crease, it would fit a bit better with the style.

**Comment by MeepyMay** [comment]
Checked in about the African braid hairstyle. We may need to change. 
## Number 1:
22657104_1516606725042631_201600213_n
## Number 2:
22709667_1516606728375964_89089874_n

We have a representation of number 1 [here](https://github.com/systers/powerup-android/blob/design/UI/avatar/hair/avatar%20hair%2014.png). If we're trying to represent number 2, we need some changes. Try more of a **bun of braids**.

**Comment by kimhwins** [comment]
Good work here with the variety of options! 

I think for the orange shirt, the texture will be out of place in the game, so a solid orange color, stripes, or a drawn-in pattern would be good alternatives.

A note about the hair that I think I briefly mentioned in the slack channel is that I think it's a little too detailed compared to the other assets and may also look out of place, so it might be good to keep in mind for future work!

**Comment by MeepyMay** [comment]
@debanjanah A couple of changes. 

1.  Black eyes --> Dark brown eyes (It's not humanly possible to have black eyes. Just dark brown.)
2. We need some outfits submitted as well. Right now, the customization is outfit-based not top/bottoms based, which can be fixed later for best diverse clothing options. (So submit both single and together design files.)
3. Can you create a "baggy" or "loose-fitting" hoodie instead? Many of the tops are already tight fitting.

**Comment by MeepyMay** [comment]
Perfect! Thank you.

**Pull request merged**
