### PR TITLE
Program GCI: Enhance the exit option in PowerUp Android

### PR DESCRIPTION
**Pull request by Aryaman21**
Done as part of the task 'Enhance the exit option in PowerUp Android'

### CODE REVIEW

**Comment by Aryaman21** [comment]
@Rimjhim28 here is the PR for my task 'Enhance the exit option in PowerUp Android'
@Rimjhim28

**Comment by Aryaman21** [comment]
@Rimjhim28 , made the changes.

**Comment by codingblazer** [comment]
@Aryaman21 Good Work !! Task approved :)

**Comment by Rimjhim28** [comment]
@Aryaman21 Do not close the PRs. We will be reviewing them to merge the best PRs. Do all the tasks by making different branches.

**Comment by Aryaman21** [comment]
Alright, ill keep that in mind from now on. @Rimjhim28

**Pull request closed without merging**
