### PR TITLE
Change room opens on start by new user

### LINKED ISSUE #42: Start change room after pressing start the first time the game is played
Currently, the change room is opened directly the first time the game is played without showing the start activity. Instead, the start activity should be shown when opening the app and then, when pressing "start" for the first time, the change room should be shown instead of the map

### PR DESCRIPTION
**Pull request by chhavip**
@alma-castant Fixed #42 . Main screen opens in either case but change room opens the first time after user presses "start". Please consider this after #45  as that will give a combined effect.

### CODE REVIEW

**Comment by chhavip** [comment]
@alma-castant. Has this PR been reviewed? Please let me know if any changes are needed.

**Comment by alma-castant** [comment]
@chhavip code looks good, but I still need to test it. I am having very busy weeks, so it may still take a little bit of time. Apologies for the delay

**Comment by alma-castant** [comment]
I just tested it and the change room is open when clicking "start" more than once as long as the application isn't closed. Where is the settings previouslyStarted value set to true?

**Comment by chhavip** [comment]
I have fixed the above issue, apologies for creating a new PR again as I have lost the old codebase. #61

**Pull request closed without merging**
