### PR TITLE
Updated compile and target SDK versions of the app

### LINKED ISSUE #1335: Update the compile and target SDK version.
## Description
The compileSdkVersion and targetSdkVersion which are set to versions 27 and 27, respectively, must be changed to 28( Android Pie) as the latest Android APIs must be used to make use of the latest features.

### Update [Required]
- [ ] Update the project level gradle file.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by moksh-mahajan**
### Description
Updated compile and target SDK versions of the app in the build.gradle file and accordingly made changes in the .travis.yml file so that there wouldn't be any license agreement issue during Travis CI test.

Fixes #1335

### Type of Change:

- Code
- Quality Assurance

### How Has This Been Tested?
I have built and tested my app on my device.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by moksh-mahajan** [comment]
@Rimjhim28 For the test to pass, I have to make changes in travis.yml file. Should I proceed?

**Comment by moksh-mahajan** [comment]
@Rimjhim28 I have changed the travis.yml for resolving the accept license agreement issue. Please review the changes.

**Review by geekanamika — COMMENTED** [review]
@moksh-mahajan This PR contains 3 commits for a very small change. Please squash the commits & update the PR.

**Comment by moksh-mahajan** [comment]
@geekanamika @Rimjhim28  Done. Please review.

**Review by geekanamika — APPROVED** [review]
Looks good to me.

**Review by Rimjhim28 — APPROVED** [review]

**Pull request merged**
