### PR TITLE
Added new scenario UI mocks (text, choices, faded stripes)

### PR DESCRIPTION
**Pull request by kimhwins**
Added:
-faded UI version
-text mockup (decided to go with just semibold)
-new dialogue boxes with the faded stripes
-choices UI mock

### CODE REVIEW

**Comment by MeepyMay** [comment]
There's a black line or cursor showing up on UI/scenario UI/gui left dialogue box.9.png at the top right of the chat bubble. @kimhwins Can you fix this?

**Comment by aanchal07** [comment]
@kimhwins Can you please resolve the conflicts?

**Comment by kimhwins** [comment]
@aanchal07  I discussed this yesterday with Dil, who will talk with May about it :) it should be resolved soon!

**Comment by aanchal07** [comment]
@kimhwins Great!

**Pull request merged**
