### PR TITLE
Fix: Enhancement in Level 2 scenarios

### LINKED ISSUE #1406: Enhancement of Library Scene in Level 2
## Description
As a user, I need The 'avatar to the right' should be placed properly 'behind the table' so that I can have a better experience of library scenario game,
so that I can experience good UI.

## Mocks
image

### Update [Required]
- [ ] The 'avatar to the right' should be placed properly 'behind the table'.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by aditmehta9**
### Description
Enhance the UI of Level 2 scenario of Hospital and Library scenarios

Fixes [# 1406](https://github.com/anitab-org/powerup-android/issues/1406)

### Type of Change:
**Delete irrelevant options.**
- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
This update in UI has been tested in 5.0 inch mobile to 6.3 inch mobile screen size.
image
image

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by aditmehta9** [comment]
As there was no common solution so we have to change the position of guardian/parent in different scenarios. So, I updated the position of character programmatically

**Comment by aditmehta9** [comment]
@m-murad @sammy1997 please review

**Comment by sammy1997** [comment]
Why did you close 2 PRs? @aditmehta9

**Comment by aditmehta9** [comment]
Because I made 2 PRs for a single issue. I thought it might be inappropriate.

**Pull request closed without merging**
