### PR TITLE
Removing error while trying to create avatar.

### LINKED ISSUE #973: Errors generated while trying to access eyes while creating Avatar
## Description
Start app for first time. Start creating the avatar. Keep watching logs. Eyes 8 and 9 generate errors. 

## Mocks
power_up_avatar

## Acceptance Criteria
- [ ] Remove this error - NoSuchFieldException caused by this.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5-10 mins

### PR DESCRIPTION
**Pull request by sammy1997**
### Description
Reduce the total number of eyes. Removes the error generated while selecting eyes when creating avatar.

Fixes #973 
### Type of Change:
- Code
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sammy1997** [comment]
@MeepyMay Can you review this? Its a small change and can be merged I guess. Thanks

**Comment by tanvidadu** [comment]
Looks good to me @MeepyMay !

**Comment by sammy1997** [comment]
@MeepyMay Please merge this.

**Comment by sammy1997** [comment]
@anubhakushwaha @MeepyMay Please review this.

**Comment by MeepyMay** [comment]
This was addressed by #826

**Pull request closed without merging**
