### PR TITLE
About button

### PR DESCRIPTION
**Pull request by MKDEVELOPEMENT**
about button is active and opens new actvity

### CODE REVIEW

**Comment by aanchal07** [comment]
There is no AboutActivity. Please add that and resubmit.

**Comment by MKDEVELOPEMENT** [comment]
I have changed the xml file, and have added the java activity. and I have added some new dimens

**Comment by anubhakushwaha** [comment]
@chhavip I think it can be closed as we have merged the work needed done in this PR via #248

**Comment by chhavip** [comment]
Closing.

**Pull request closed without merging**
