### PR TITLE
Animation effect is shown when back button is pressed.

### LINKED ISSUE #1348: Animation should me shown when back button is pressed in the game map screen.
## Description
In the game map screen, when a building is clicked, then a nice animation effect is shown when the screen changes from map to conversation scenario. Also when the user goes back to map screen from any conversation screen using the home button (on the top right corner), then also the animation effect is shown. 
But when the **back button** is pressed, this animation effect is not shown. My idea is to add this animation effect when the back button is pressed too.
### Update [Required]
- [x] Add the animation effect when back button is pressed.

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by moksh-mahajan**
### Description
I have included the code for showing the animation efffect while returning from a game or conversation screen to the map screen when back button is pressed. Previously, this effect was only shown when the home icon on the top right corner was pressed.

Fixes #1348 

### Type of Change:

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
The app has been built and tested for the implemented feature successfully.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by moksh-mahajan** [comment]
@Rimjhim28 @geekanamika Please review this PR.

**Review by Rimjhim28 — APPROVED** [review]
LGTM

**Comment by atm1504** [comment]
Hey @moksh-mahajan, when u r creating a, pr it's a good habit that you start the Pull request title using words like ```feat: or chore: or fix: ``` depending on the task you r solving.
For example, here you should have started like ```feat: Add animation on back press```
Please try to follow this.

**Review by atm1504 — APPROVED** [review]
LGTM

**Review by sammy1997 — APPROVED** [review]
LGTM

**Pull request merged**
