### PR TITLE
Add about page

### PR DESCRIPTION
**Pull request by FarbodSalamat-Zadeh**

### CODE REVIEW

**Comment by chhavip** [comment]
@anubhakushwaha , @FarbodSalamat-Zadeh @aanchal07 , is this PR for a GCI task and has it been approved? Please comment so appropriate future action can be taken.

**Comment by anubhakushwaha** [comment]
@chhavip **Yes it was approved** after the student persistently trying to resolve the conflicts.Here is the approval https://codein.withgoogle.com/dashboard/task-instances/4833748178698240/

**Comment by anubhakushwaha** [comment]
@chhavip This can be closed as it is now a redundant PR .Fixed via #248

**Comment by chhavip** [comment]
Closing.

**Pull request closed without merging**
