### PR TITLE
Program: GCI Improper handling of Back button

### PR DESCRIPTION
**Pull request by ValentunSergeev**
Hey, I've completed the issue #503, now back pressing returns user to the main screen

### CODE REVIEW

**Comment by Rimjhim28** [comment]
@ValentunSergeev You need to include the link on GCI portal and submit it to review so that your work can be reviewed by the mentors.

**Comment by ValentunSergeev** [comment]
@Rimjhim28 thanks, did it.

**Comment by Rimjhim28** [comment]
@ValentunSergeev Have you fetched the code from "GSoC17"? It seems like you are on the wrong branch.

**Comment by ValentunSergeev** [comment]
@Rimjhim28 no, I was in develop branch. So just looked on GSoC17, there is no Complete Scene Activity. What I should do?

**Comment by Rimjhim28** [comment]
@ValentunSergeev Navigate to the GSoC17 branch and fetch the code. Do the required changes there. Also explore the game to identify where the changes should be made.

**Comment by ValentunSergeev** [comment]
@Rimjhim28 so, as I understood, I should add this back functionality to all activities which represents end of the part of the game, such as:
* SinkToSwimEndActivity.java
* VocabMatchEndActivity.java
* ScenarioOverActivity.java
Am I right?

**Comment by Rimjhim28** [comment]
Yes @ValentunSergeev you are right. But also there are other activities where the back button needs a proper implementation. Explore the app to identify more activities where the implementation can be done.

**Comment by ValentunSergeev** [comment]
@Rimjhim28 I've finished. Also, I've done some refactoring to reduce code duplication.

**Comment by Rimjhim28** [comment]
@ValentunSergeev Please make PR to GSoC17 branch. Also squash all your commits to one.

**Comment by ValentunSergeev** [comment]
@Rimjhim28 So, i changed the base of PR to GSoC17, and there's three not mine commits, may be from develop branch. Is it acceptable, or I should create a new branch from GSoC17, make changes again and create a new PR?

**Comment by ValentunSergeev** [comment]
I decided to open a new  #PR(#602), so it should be closed

**Pull request closed without merging**
