### PR TITLE
Enhancing User Experience in AvatarRoomActivity

### LINKED ISSUE #1413: Enhancing User Experience in AvatarRoomActivity
## Description
The current avatar room does not show button clicks.
This would be helpful in enhancing user experience.

## Before
WhatsApp Video 2020-03-24 at 4 21 51 PM

## After
WhatsApp Video 2020-03-24 at 4 19 00 PM

### PR DESCRIPTION
**Pull request by pknotfound**
### Description
Enhanced the User Experience by showing touches in Avatar room Activity

WhatsApp Video 2020-04-13 at 6 45 09 PM

Fixes #1413

### Type of Change:
- Code

### How Has This Been Tested?
Tested on OnePlus6t

### CODE REVIEW

**Review by sammy1997 — APPROVED** [review]
LGTM

**Comment by sammy1997** [comment]
@Priyansh-Kedia Can you add the GIF of the working feature in the description? Also, please edit the PR title removing the Re:

**Comment by pknotfound** [comment]
> @Priyansh-Kedia Can you add the GIF of the working feature in the description? Also, please edit the PR title removing the Re:

Sure 
I will do it right away.

**Comment by sammy1997** [comment]
Merging this

**Pull request merged**
