### PR TITLE
Added new clothes and accessories for girl's avatar

### PR DESCRIPTION
**Pull request by KateRazumova**
Added two dresses, a pajama, a singlet, two hawaiian flowers and a bow.

### CODE REVIEW

**Comment by kimhwins** [comment]
nice work creating so many options!!

glancing over it, one of my concerns would be the glasses look a little flimsy/might look out of place--could you post a picture of the glasses on the avatar with other clothes as well? I also mentioned this earlier in the slack channel, but I think the dresses may be too detailed compared to the other clothes available.

**Comment by kimhwins** [comment]
Thanks so much for the compilations! Looking at it now, I would add that I think adding a sort of horizontal line in the crotch area of the pants/shorts/leggings would be helpful!

Sort of like this: 
image

**Comment by MeepyMay** [comment]
@KateRazumova What I notice, is that these don't have the same dimensions as the current avatar items. The .PNG files themselves have a lot of transparent space to fit the avatar. Also, the newer version does full outfits, it doesn't have the same functionality as before (for example, several shirts and several bottoms to pick from). In later versions, we can separate, but for the purpose of the minimum functional product, we'll do simple random outfits. We can have them customize later. :) (i.e. choose a shirt, then choose color from a color wheel)

Cleared Elements (fits style best): 
- bow
- earrings
- hair band
- round earrings
- skirts (plain ones)
- T-shirts
- blouse
- sweater
- striped singlet (tank top, [blue](https://github.com/KateRazumova/powerup-android/blob/c0a97e74dac2c616e5e561d8c1d339ff9c3b8083/UI/avatar/clothes/avatar%20singlet%20long%20blue%20striped%20.png) and [orange](https://github.com/KateRazumova/powerup-android/blob/c0a97e74dac2c616e5e561d8c1d339ff9c3b8083/UI/avatar/clothes/avatar%20singlet%20long%20orange%20striped%20.png))

Uncleared Elements (not in line with style): 
- new eyes (we met with the original designer in GSoC, anime eyes are not being used for this app right now due to the original user research)
- avatar dress yellow/red (this has an incredible amount of details and lines, the neck straps are also a little low)
- striped singlet
- striped skirt

Can you send in some pre-created outfits in dimensions such as the dress? 
Is it possible to get samples with African American skin tones?

Some of these elements also have shaded areas, our version 1.0 is flat first with bold lines, later versions (after user testing and research) will improve based on their feedback. Shading, possible anime eyes, etc. 

Thank you @KateRazumova!

**Comment by MeepyMay** [comment]
@KateRazumova Can you create a second folder called **version3-beta** so we can use these design elements in user A/B testing in schools?

**Comment by KateRazumova** [comment]
@MeepyMay Can you clarify, what should I add in a **version3-beta** folder?

**Pull request merged**
