### PR TITLE
Fix: Removed obsolete layout params #1102

### LINKED ISSUE #1102: Fix lint errors
## Description
As a maintainer,
I need remove the lint errors in the code,
so that the overall code structure and app performance can be improved.

## Mocks
Not applicable

### Update 

The warnings/error that need to fixed are
- [ ] Android Resource Validation ( 8 errors )
- [ ] Extraneous text in resource file ( 1 waining )
- [ ] Missing commit() on SharedPreference editor ( 4 warnings )
- [ ] Wrong Resource Type ( 4 warnings )
- [ ] Hardcoded text ( 27 warnings )
- [ ] TextView Internationalization ( 18 warnings )
- [ ] Using left/right instead of start/end attributes ( 3 warnings )
- [ ] FrameLayout can be replaced with <merge> tag ( 5 warnings )
- [ ] Missing baselineAligned attribute ( 5 warnings )
- [ ] Obsolete layout params ( 5 warnings )
- [ ] Pointless boolean expression ( 4 warnings )
- [ ] Redundant local variable ( 4 warnings )
- [ ] Declaration can have final modifier ( 27 warnings )
- [ ] Method can be void ( 1 warning )
- [x] Redundant throws clause ( 22 warnings )
- [x] Unused import ( 40 warnings )
- [ ] 'if' replaceable with 'switch' ( 3 warnings )
- [x] Unused XML schema declaration ( 5 warnings )

**Note** : Only of the above listed items can be claimed and fixed by one contributor

## Definition of Done
- [ ] One of the required item is completed
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by nidhinmahesh**
### Description
Removed Obsolete attributes (5/5)

Fixes #1102 

### Type of Change:
removed unused attributes. All screens remains unaffected.
photo_2019-01-25_18-53-10
photo_2019-01-25_18-52-59

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Rimjhim28 — CHANGES_REQUESTED** [review]
@nidhinmahesh While the changes look good, could you please post the screenshots of the screens that you have worked on so the we cam be sure that the deletions have not affected anything?
Also, add "Fix: " before your commit message so that it is clear that the commit intends to fox a previous issue.

NOTE: Please have a look at the contribution guidelines. Submit a PR only after you are assigned to an issue. We might already have a contributor working on the same, so it's better to ask beforehand. Please take care of this in your future contributions! :)

**Comment by nidhinmahesh** [comment]
> @nidhinmahesh While the changes look good, could you please post the screenshots of the screens that you have worked on so the we cam be sure that the deletions have not affected anything?
> Also, add "Fix: " before your commit message so that it is clear that the commit intends to fox a previous issue.
> 
> NOTE: Please have a look at the contribution guidelines. Submit a PR only after you are assigned to an issue. We might already have a contributor working on the same, so it's better to ask beforehand. Please take care of this in your future contributions! :)

thank you! I will do it.

**Review by Rimjhim28 — CHANGES_REQUESTED** [review]
@nidhinmahesh I asked to changed the "Commit message" by adding "Fix: ".
You can view the commit message in the ```commits``` tab.

**Comment by nidhinmahesh** [comment]
> @nidhinmahesh I asked to changed the "Commit message" by adding "Fix: ".
> You can view the commit message in the `commits` tab.

@Rimjhim28 I made the changes you have asked for. Thanks for helping out!

**Review by Rimjhim28 — CHANGES_REQUESTED** [review]
@nidhinmahesh Please squash the commits.
Have a single commit with the most appropriate commit message.

**Comment by nidhinmahesh** [comment]
I have squashed the commits. Please check.

**Comment by geekanamika** [comment]
@nidhinmahesh I can still see 5 commits on PR. If you are having problem with squashing commits, ask it on slack & someone might help you :)
image

**Comment by nidhinmahesh** [comment]
@geekanamika Thanks.. I fixed it!. @Rimjhim28 please review.

**Review by Rimjhim28 — APPROVED** [review]
LGTM

**Pull request merged**
