### PR TITLE
Back Button Fix (Space also fixed)

### PR DESCRIPTION
**Pull request by Aryaman21**
Corrected all the extra spaces and the back button functionality

### CODE REVIEW

**Comment by Rimjhim28** [comment]
@Aryaman21 Seems like you removed some pre-existing lines. Try only to add your code without touching the other parts. Also the migration from VocabMatch and SinkToSwim to StartActivity is wrong. Try to figure out what should be coorect migration. You have also missed to add the implementation in one more activity. Please do the changes by modifying your current PR and commit instead of creating a new one. Make sure that you've commited the changes properly.

**Comment by Aryaman21** [comment]
Now I hope I have fixed the errors.

**Comment by Rimjhim28** [comment]
@Aryaman21 Please squash your commits to one. Remove the .gitignore file from the commit.

**Comment by Aryaman21** [comment]
@Rimjhim28 Done the changes

**Comment by Aryaman21** [comment]
@Rimjhim28 The changes made were done when i was told to delete extra spaces in the code, and i believe those are the ones occurring more frequently.

**Comment by Aryaman21** [comment]
When i run the app and debug the flow of control, I cannot reach Minesweeper activity from any instance, this requires for a fix in flow of control and i think a new task should be created to fix this, i'll be glad to fix it. I've fixed the back button functionality as requested, and the back button parameter of the flow of control is now in order according to me, also implemented the latest changes requested, except the MineSweeperActivity as it's not a part of the back button functionality problem.
Commited new changes

**Comment by Aryaman21** [comment]
@Rimjhim28 @Rimjhim28 Please review the latest changes as soon as possible, please i really want to get my other tasks reviewed as well. Also please add some tasks for designing, I even had some ideas for the splash screen. @Rimjhim28

**Comment by Rimjhim28** [comment]
@Aryaman21 Nice work i've approved the task. Tasks related to designing already exist. If you're not able view those it may be because they were claimed before by other students and would be available again once they have submitted thier work. We'll be coming come with new tasks in weeks to com. :)

**Comment by Aryaman21** [comment]
Yes, I see the problem here, I was still in my beginner phase of using Github and seem to have overridden the commit in the same branch, I'm in the process of retrieving the data and would like to create a new PR for this task because this branch is associated with https://github.com/systers/powerup-android/pull/622. Would that be alright? @Rimjhim28

**Comment by Rimjhim28** [comment]
@Aryaman21 It is absolutely fine since your work was present during approval.I have already selected the beat one to be merged so you don't need to bother about opening another. I am documenting all PRs that are related to GCi. If any work would be required from your side I will contact you directly.

**Comment by Aryaman21** [comment]
Okay, Alright 👍, If anything else comes up or if you need me to anything new, please ping me.

**Pull request closed without merging**
