### PR TITLE
Adds Scenarios to the Game

### PR DESCRIPTION
**Pull request by codingblazer**
Adds hospital scenario as suggested in #385

### CODE REVIEW

**Comment by aanchal07** [comment]
@codingblazer Can you send this PR to the branch GSoC17?

**Comment by codingblazer** [comment]
@aanchal07 Yeah sure !!

**Comment by codingblazer** [comment]
@aanchal07 Added Library Scenario too !!

**Comment by aanchal07** [comment]
@codingblazer I tested the hospital scenario and I could not scroll down on this screen, can you double check?
image.

**Comment by codingblazer** [comment]
@aanchal07 I added scrollview but it isn't looking good due to bottom Health & Power Bar. What do you suggest? Should I add scrollview or reduce the content (which is going to happen anyway as per  @may)

**Comment by aanchal07** [comment]
@codingblazer Use a scrollview

**Comment by codingblazer** [comment]
@aanchal07 Added Scrollview, please review :-)

**Pull request merged**
