### PR TITLE
Swim to Sink Game 

### PR DESCRIPTION
**Pull request by codingblazer**
Adding Swim to Swim Mini-Game to PowerUp Project.

### CODE REVIEW

**Comment by aanchal07** [comment]
Looks good to me, just the animation of the boat sinking can be better. But that can be improved in the phase 3.
@dhara04 Can you also look at the PR once?

**Comment by dhara04** [comment]
Looks good to me as well. As we discussed in Monday's meeting: we need to work a bit on the animation side. The boat misses going up a few times. Other than that I saw a minor inconsistency with the iOS app(demo shared by Yu), where after  playing the mini game, the next screen shows a pop-up saying" Hooray, you scored x Karma points". We need to make this functionality consistent across Android and iOS.

**Comment by aanchal07** [comment]
@codingblazer Are you done with these changes?

**Comment by codingblazer** [comment]
@aanchal07 Actually I have done the animation changes in a separate branch (the one with the UI additions). I will send PR for it soon.  :-)

**Comment by aanchal07** [comment]
@codingblazer Okay.
@dhara04 Should we go through this PR again? Or merge it with the current functionalities?

**Pull request merged**
