### PR TITLE
Display an exit warning on back press.

### PR DESCRIPTION
**Pull request by m-sameer**
Fixes issue #576

### CODE REVIEW

**Comment by Rimjhim28** [comment]
@m-sameer Great work! Please dont change other parts of code. Please add only the part relevant to the task. Try doing this in a single commit

**Comment by m-sameer** [comment]
I changed the `import` statements back to how they were.

**Comment by Rimjhim28** [comment]
@m-sameer I think you have not submitted the work to review. Please do that :)

**Comment by m-sameer** [comment]
@Rimjhim28 I have done the changes and have submitted the work for review. Thanks for helping :)

**Comment by Rimjhim28** [comment]
@m-sameer You have added an extra line. Remove that.

**Comment by m-sameer** [comment]
Above the `override` statement?

**Comment by Rimjhim28** [comment]
@m-sameer Remove the extra line above the override statement.

**Comment by m-sameer** [comment]
It's the space between two functions according to the Java coding conventions. Do you still want me to remove it?

**Comment by m-sameer** [comment]
@Rimjhim28 Did the change :)

**Comment by m-sameer** [comment]
Thank you. :)

**Pull request closed without merging**
