### PR TITLE
Fixes #88

### LINKED ISSUE #88: Retain of AppState on Orientation Change
Currently on changing the orientation of App.The AppState gets lost and we are set to default one.

While Writing test for PR #87 ,I encountered this.
I will make a PR to fix this shortly. :smile:

### PR DESCRIPTION
**Pull request by opticod**
#88

### CODE REVIEW

**Comment by alma-castant** [comment]
Please @opticod describe the fix in the PR body and commit message, not only a link to the issue

**Comment by opticod** [comment]
@alma-castant Currently in `AvatarRoomActivity` ,the app doesn't retail app state while orientation change.This means that ,on changing orientation you have to restart making selection from beginning.This will create problem to users .Hence here is a fix for that.

**Comment by alma-castant** [comment]
@opticod please change the message in your commit, as that is what is seen when commits are merged. The commit message should briefly but clearly describe what the commit does

**Comment by opticod** [comment]
@alma-castant done

**Comment by opticod** [comment]
Presently, in game activity also have a similar bug like this...there list of conversation gets revert to original one probably loosing score...can i make a pr for fixing them too? @alma-castant

**Pull request closed without merging**
