### PR TITLE
Project: GCI - Task Remove all hardcoded strings in the project

### PR DESCRIPTION
**Pull request by aviral2004**
This is my PR request for the Google Code-In competition

### Description
I have removed most of the hardcoded strings and changed them to res values 

Fixes # [ISSUE]

### Type of Change:
- Code

### Checklist:
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by Rimjhim28 — COMMENTED** [review]
Submission to GCI Task 9. Used the most generalized names. Best to be merged.

**Comment by Rimjhim28** [comment]
Will be merged directly to develop after moving all the changes.

**Review by Rimjhim28 — APPROVED** [review]

**Comment by Rimjhim28** [comment]
@geekanamika Can you please look into this. There isn't an option to resolve the conflicts through develop.

**Review by r00pal — APPROVED** [review]

**Review by Rimjhim28 — COMMENTED** [review]
@aviral2004 Please resolve the conflicts

**Review by Rimjhim28 — COMMENTED** [review]
Since there isn't any reply on the PR, I am closing it.

**Pull request closed without merging**
