### PR TITLE
Create a screen for "Not Enough Points" condition

### PR DESCRIPTION
**Pull request by InfernoCoder**
I fixed [this issue](https://github.com/systers/powerup-android/issues/170) and this is the PR.

**PS: My last PR had problems, so I closed that and created this PR.**

### CODE REVIEW

**Comment by aanchal07** [comment]
When there are not enough points you are showing a snackbar. Now on clicking the "OK" in the snackbar, the app is not going anywhere so make the user go to the avatar activity with no changes in the avatar.

**Comment by InfernoCoder** [comment]
@aanchal07 I fixed t

**Comment by InfernoCoder** [comment]
@aanchal07 I fixed it in the latest commit.

**Comment by aanchal07** [comment]
Great work!

**Comment by aanchal07** [comment]
Closing the pull request since there are conflicts.

**Pull request closed without merging**
