### PR TITLE
Power Bar UI fixed

### PR DESCRIPTION
**Pull request by chhavip**
I apologize for this being the third PR for the same task with 3 commits but I didn't squash them as it is leading to more errors, I have included the gradle file so the dependency is included and errors mentioned are also fixed.

### CODE REVIEW

**Comment by alma-castant** [comment]
Don't worry about having 3 commits for now. The bars should be showing the current value of the different powers. Right now they are always showing zero.
I would also recommend testing in landscape mode and in bigger displays, as the bars are not adapted to those scenarios yet

**Comment by chhavip** [comment]
@alma-castant , there is no logic in the game handling the values of the powers yet, what should I set them to?
I will make adapting it to different sizes a separate issue and work on it, will help keep things cleaner.

**Comment by alma-castant** [comment]
I thought the `Score` class was holding the current values, but I was wrong. Could you then set the current values of the bars to something different than zero for now so it is easier to spot issues? Let me know when you have adapted it to landscape and big screens ;)

**Comment by chhavip** [comment]
I will update the values to something different, as for adapting it to bigger screens, I see that the entire game screen needs to be adapted for larger screens, wouldn't it be better if that is an entirely separate issue? Or should I fix just the power bars for big screens in this PR and submit?

**Comment by alma-castant** [comment]
I know many things haven't been made for all screen sizes and there are many issues opened to solve this, but new features should be built for all devices and orientations so we don't add issues to the application

**Comment by chhavip** [comment]
@alma-castant , a value for all the progress bars has been set and they have been fixed for various landscape and portrait modes. Because of various merges, there are too many commits in this PR, let me know if revisions are required.

**Comment by alma-castant** [comment]
Hi @chhavip sorry for taking a bit long to review. The branch has conflicts now. Could you fetch and resolve the conflicts so I can test it? I suggest using the opportunity to have only 1 commit here. Feel free to create a new PR if needed

**Comment by chhavip** [comment]
New PR submitted.

**Pull request closed without merging**
