### PR TITLE
Program:GCI Enhance the exit option

### PR DESCRIPTION
**Pull request by HITGIF**
Now, pressing the back button once in StartActivity will display a toast message "Press once more to exit".
Pressing the back button again within 2 seconds will exit the game.
screenshot_1512016977

### CODE REVIEW

**Comment by Rimjhim28** [comment]
@HITGIF Make sure that you first claim the task on GCI portal and submit it to review there. There are specific steps mentioned in the task. Follow all of them. Use the latest code that is in "GSoC17" branch.

**Comment by HITGIF** [comment]
@Rimjhim28 Yeah I know that.
I'm currently on another task and I'll claim this one once I got that reviewed

**Comment by HITGIF** [comment]
@Rimjhim28 Also I got an error `fatal: invalid reference: GSoC17` when trying to switch to the GSoC17 in Github Desktop.
image
Can you help me?

**Comment by Rimjhim28** [comment]
Instead try using git terminal. You will get to know much more about VCS.

**Pull request closed without merging**
