### PR TITLE
Fixes #296:ScenarioNames issue in GameActivity in landscape mode

### LINKED ISSUE #296: ScenarioNames issue in GameActivity in landscape mode
ScenarioNames TextView  in  GameActivity is not displaying properly in landscape mode and the text is cutting with the background layout.

**Screen Shots**
whatsapp image 2017-01-30 at 1 04 18 pm 1
whatsapp image 2017-01-30 at 1 04 18 pm 2
whatsapp image 2017-01-30 at 1 04 18 pm 3
whatsapp image 2017-01-30 at 1 04 18 pm

@chhavip @yatna @anubhakushwaha If this is a valid issue can I work on this and send the PR for the same?

### PR DESCRIPTION
**Pull request by HimanshuS01**
**Following are the screenshots of the changes I have made**
device-2017-02-04-120526
device-2017-02-04-120551
device-2017-02-04-120630
device-2017-02-04-120713

@anubhakushwaha @chhavip @aanchal07  Please review this PR. Thanks :)

### CODE REVIEW

**Comment by aanchal07** [comment]
Looks good to me. Checked on emulator too.
@chhavip @anubhakushwaha Recheck and merge.

**Comment by chhavip** [comment]
@HimanshuS01 Please resolve the conflicts before it can be merged.

**Comment by HimanshuS01** [comment]
@chhavip I have resolved the conflicts. Please review and merge this PR.Thanks :)

**Comment by anubhakushwaha** [comment]
@HimanshuS01 Please check it on as many devices of diff screen sizes and see if you have adjusted according to all.For instance,I tried it on Nexus-5 here's how it looks.
pr

**Comment by HimanshuS01** [comment]
Sure @anubhakushwaha. I will check and handle the UI on different screen sizes soon.

**Comment by HimanshuS01** [comment]
@anubhakushwaha I have checked the UI on Nexus S(4''),Nexus 4(4.7''),Nexus 5',Nexus 5X  devices.
Now it's  working properly.Please check and review this PR. Thanks

**Comment by chhavip** [comment]
Looks good to me. Code is also fine. Let me know if we this should be merged @aanchal07 @anubhakushwaha

**Comment by HimanshuS01** [comment]
@anubhakushwaha @aanchal07 please review this issue.
_Thank you_ :)

**Comment by anubhakushwaha** [comment]
@chhavip It can be merged.

**Pull request merged**
