### PR TITLE
Shoe colour

### PR DESCRIPTION
**Pull request by Ph0ebe**
Changed the colour of the shoes for each of the images cloth*.png in the drawable directory.

### CODE REVIEW

**Comment by anubhakushwaha** [comment]
@Ph0ebe please take care to give a meaningful commit message describing what exactly your PR is trying to resolve. @chhavip **It is an approved GCI task** *link to the approved task* https://codein.withgoogle.com/dashboard/task-instances/5399493753176064/

**Comment by Ph0ebe** [comment]
Hi @anubhakushwaha I have changed the commit message to something that describes what I did. Let me know if this is ok.

**Comment by anubhakushwaha** [comment]
@Ph0ebe Yes,it's good now,thanks :+1:

**Comment by anubhakushwaha** [comment]
@chhavip This can be closed as it's redundant PR now after merging #301

**Comment by aanchal07** [comment]
Conflicts in the PR.

**Pull request closed without merging**
