### PR TITLE
Fixes #998 Rectify implementation of warning dialog

### LINKED ISSUE #998: Rectify the implementation of warning dialog in store
## Description

With recent changes in the code, a warning dialog is implemented to warn the user prior to buying an item. The item gets already set on avatar before user's decision whether it should be bought or not.
A rectification is needed here such that, clicking on the item first presents the dialog and only if the userconfirms, the item is bought.

## Mocks

videotogif_2018 02 14_13 03 58

### Update 
- [ ] Rectification of function showConfirmPurchaseDialog()

## Definition of Done

- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation

1 hour

**I would like to work on the issue**

### PR DESCRIPTION
**Pull request by Rimjhim28**
### Description
Implementation of warning dialog such that the item selected by the user apperas ion the Avatar only if she decides to purchase it
Fixes #998

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
The changes were checked in android studio emulator
store warning

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Rimjhim28** [comment]
@m-murad Please have a look.

**Comment by m-murad** [comment]
Thanks for the PR.
But this PR creates another issue. 
Currently, the user is not able to try the item before buying it. 

Can you create an issue for this and fix it in another PR.

**Comment by Rimjhim28** [comment]
@m-murad In a way that if the user chooses an item it appears on avatar.
Now if she confirms the purchase the item remains on avatar and if she declines by choosing "maybe not" the avatar resets to what it was previously. Right??

**Comment by geekanamika** [comment]
@m-murad There won't be need of another issue. I've mentioned the same concern in #1069 . Since, Rimjhim mentioned that she has resolved it in her PR , i have closed it temporarily. 
I would like to solve it if you can approve :)

**Comment by Rimjhim28** [comment]
@geekanamika I was just waiting for @m-murad to reply. I adjusted theimplementation as it was before and is in iOS version. Trying before buying would be a new feature and would require a community decision before working.

**Comment by geekanamika** [comment]
I've re-opened the issue & added enhancement label on it. We can discuss it on slack before going further.

**Comment by m-murad** [comment]
looks good, please remove the merge conflict.

**Pull request merged**
