### PR TITLE
Correct accessories

### PR DESCRIPTION
**Pull request by MKDEVELOPEMENT**
avatar is supposed to be corrected

### CODE REVIEW

**Comment by anubhakushwaha** [comment]
@MKDEVELOPEMENT As asked try resolving the conflicts and your DressingRoomActivity along with addition of corresponding .xml files of updated activities.

**Comment by chhavip** [comment]
@MKDEVELOPEMENT Please also provide a better title and description*(including the purpose) to the PR and the respective GCI task if it is for the fulfillment of one.

**Comment by anubhakushwaha** [comment]
@MKDEVELOPEMENT Please close this PR as you have already sent another for the same.

**Comment by chhavip** [comment]
I ll be closing this as it seems it is not needed anymore. Let me if know if the case is otherwise.

**Pull request closed without merging**
